services:
  db:
    container_name: example_db
    image: "postgres:17.6"
    restart: always
    environment:
      POSTGRES_USER: example_app
      POSTGRES_PASSWORD: test
      POSTGRES_DB: example_db
    ports:
      - "5432:5432"
